---
title: "Einführung in die Datenanalyse mit R"
author: "Jan-Philipp Kolb"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Unterlagen für den Kurs 2019. Die Foliensätze sind [hier](slides/Intro_Datenanalyse1.md) verfügbar. Das pdf und die Browser Version für die einzelnen Teile sind ebenfalls in diesem Github Ordner enthalten. Der rcode in den Folien lässt sich mit den Dateien im [rcode Ordner](https://github.com/Japhilko/IntroR/tree/master/2019/rcode) nachverfolgen. 

## Einführung und Vorbereitung

- Warum R eine gute Wahl ist. ([Browser](slides/WarumR.md) |  [pdf](slides/WarumR.pdf) )

- Dein Freund das GUI ([Browser](slides/FreundGUI.md) | [pdf](slides/FreundGUI.pdf))

    - Aufgabe: Vorbereitung ([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/tutorial/Aufgabe_Vorbereitung.md))


- Grundlagen im Umgang mit der Sprache R ([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/slides/GrundlagenR.md) | [pdf](slides/GrundlagenR.pdf) | [rcode](https://github.com/Japhilko/IntroR/blob/master/2019/slides/GrundlagenR.R) )

    - Aufgabe: Zuweisungen und Funktionen ([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/tutorial/Aufgabe_Zuweisung.md))


- Wie bekommt man Hilfe? ([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/slides/Hilfe.md) |
[pdf](slides/Hilfe.pdf) |
[rcode](https://github.com/Japhilko/IntroR/blob/master/2019/slides/Hilfe.R))

- Modularer Aufbau von R ([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/slides/ModularerAufbau.md) |
 [pdf](slides/ModularerAufbau.pdf) | [rcode](https://github.com/Japhilko/IntroR/blob/master/2019/rcode/InstallPackages.R))

    - Aufgabe Zusatzpakete ([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/tutorial/Aufgabe_Zusatzpakete.md))

## Rein und raus – Datenimport und -export


- Datenimport ([Browser](slides/Import.md) | [pdf](slides/Import.pdf) | [rcode](slides/Import.R))

    - Aufgabe Datenimport ([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/tutorial/Aufgabe_Datenimport.md))

- Datenexport ([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/slides/Export.md) | [pdf](slides/Export.pdf) | [rcode](slides/Export.R))

## Ein erster Eindruck – Was uns die Daten sagen

- Das GESIS Panel ([pdf](slides/GESISPanel.pdf))

<!--
- Indizieren
([Browser](slides/datenanalyse_ffm.Rmd)| [pdf](slides/datenanalyse_ffm) |  [rcode](https://github.com/Japhilko/IntroR/blob/master/2019/rcode/datenanalyse_ffm.R))
-->

- Datenverarbeitung ([Browser](slides/DatenVerarbeitung.Rmd) | [pdf](slides/Datenanalyse.pdf) | [rcode](rcode/Datenanalyse.R))

    - Aufgabe - Apply Funktion verwenden ([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/tutorial/Aufgabe_Apply.md))

## Liebe auf den ersten Plot – Grafiken mit R	

- Einfache Grafiken
([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/slides/EinfacheGrafiken.md) | [pdf](slides/EinfacheGrafiken.pdf) | [rcode](rcode/EinfacheGrafiken.R))

    - Aufgabe - Barplot ([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/tutorial/Aufgabe_Barplot.md))
    
## Noch mehr Grafiken - multidimensional

- Zusammenhang ([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/slides/Multidimensional.md) | [pdf](slides/Multidimensional.pdf) | [rcode](rcode/Multidimensional.R))

- Das lattice Paket ([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/slides/LatticePaket.md) | [pdf](slides/LatticePaket.pdf) | [rcode](rcode/LatticePaket.R))

    - Aufgabe - OECD Datensatz ([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/slides/Aufgabe_OECDdata.md))
    
    
## Regression – Überblick der Methoden in R

- Die lineare Regression ([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/slides/LineareRegression.md) | [pdf](slides/LineareRegression.pdf) | [rcode](rcode/LineareRegression.R))

    - Aufgabe - lineare Regression ([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/tutorial/Aufgabe_LineareRegression.md))

- Die logistische Regression ([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/slides/logistischeRegression.md) | [pdf](slides/logistischeRegression.pdf) | [rcode](rcode/logistischeRegression.R))

    - Aufgabe - Datenanalyse ([Browser](https://github.com/Japhilko/IntroR/blob/master/2017/tutorial/Aufgabe_Datenanalyse.md))

## Ausblick – Möglichkeiten mit R


- Exkurs: Datenquellen ([Browser](https://github.com/Japhilko/IntroR/blob/master/2019/slides/Datenquellen.md))


- Faktoren in R ([Browser](https://github.com/Japhilko/IntroR/blob/master/2017/slides/Faktoren.Rmd) | [pdf](https://github.com/Japhilko/IntroR/blob/master/2017/slides/Faktoren.pdf) | [rcode](rcode/Faktoren.R))

- Grafiken mit ggplot ([Browser](https://github.com/Japhilko/IntroR/blob/master/2017/slides/ggplot2.Rmd) | [pdf](https://github.com/Japhilko/IntroR/blob/master/2017/slides/ggplot2.pdf) | [rcode](rcode/ggplot2.R))

- Beispiel einer [interaktiven Karte](http://rpubs.com/Japhilko82/Campsites) und [Rcode](https://raw.githubusercontent.com/Japhilko/GeoData/master/2015/rcode/SpatMA_Interactive%20maps.R) um eine interaktive Karte mit leaflet zu erzeugen.
